### PR TITLE
Add metric: rate of change (roc)

### PR DESCRIPTION
**Pull request by LylChun**
Add four functions: roc vector, sd of roc, histogram, and time series plot

### CODE REVIEW

**Comment by irinagain** [comment]
Hi Lizzie! Awesome job on these new metrics. I have a couple of quick comments:
- for documentation, can you please utilize @inheritParams (see lasagna_plots.R for an example of that in plot_lasagna_1subject function)? This will avoid duplication of explaining the parameters, and this way if description changes in one place, it will automatically change in all the other places as well
- for roc, is my understanding correct that a vector of all values is returned? I think the documentation states two columns (see @return) so I am double checking

**Review by irinagain — CHANGES_REQUESTED** [review]
Hi Lizzie! Awesome job on these new metrics. I have a couple of quick comments:

- for documentation, can you please utilize @inheritParams (see lasagna_plots.R for an example of that in plot_lasagna_1subject function)? This will avoid duplication of explaining the parameters, and this way if description changes in one place, it will automatically change in all the other places as well

- for roc, is my understanding correct that a vector of all values is returned? I think the documentation states two columns (see @return) so I am double checking

**Comment by LylChun** [comment]
Thanks for your feedback! I've just updated the documentation to use @inheritParams. 

For your second comment, the function roc does not produce a vector. It produces a tibble with 2 columns - the first is the subject id and the second is the roc values. When I wrote the PR description I called it a roc vector just because that's what the original spreadsheet said and I didn't stop to think about it, sorry for the confusion! If you actually want it to be a vector, I can strip the subject id column and have the function just return a vector, but I don't think this would work well for datasets with more than one subject because you would have no way of telling where one patient's data ends and the next begins.

**Comment by irinagain** [comment]
Additional minor things: add your name to DESCRIPTION as one of the authors, and change the version to 1.2.0. Add author designation via @author (see example here: https://github.com/refunders/refund/blob/master/R/fpca.face.R)

**Comment by LylChun** [comment]
I've finished all the edits you mentioned, if there's anything else you would like me to fix just let me know!

**Pull request merged**
